Repository octokit/request-error.js, pull requests merged in 2022-07, with the labels that each got.

#236 ci: stop testing against NodeJS v10, v12
  .github/workflows/test.yml
  package.json
Labels: blocked, maintenance

#238 ci(test): use test_matrix and test jobs
  .github/workflows/test.yml
Labels: maintenance

#242 [deps] updates pika/pack to a non vulnerable version
  package-lock.json
  package.json
Labels: dependencies, maintenance
