Repository octokit/request-error.js, pull requests merged in 2023-05, with the labels that each got.

#334 docs(README): add example for error handling
  README.md
Labels: Type: Maintenance

#335 docs(README): remove self-referencing comment from Octokit usage example
  README.md
Labels: Type: Documentation

#331 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package.json
Labels: Type: Breaking change, Type: Maintenance
